server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: django_app
    static_configs:
      - targets:
          - localhost
        labels:
          job: django
          __path__: /app/logs/*.log

    pipeline_stages:
      - regex:
          expression: '^\[(?P<ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})\] (?P<level>[A-Z]+) (?P<logger>\w+) (?P<msg>.*)$'

      - timestamp:
          source: ts
          format: "2006-01-02 15:04:05,000"

      - labels:
          level:
          logger:

      - output:
          source: msg